name: Deploy
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: extractions/setup-just@v2
      - run: just install
      - run: just build
      - run: just package
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  gh_release:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -R
      - uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            dist/*

  pypi_release:
    needs: build
    runs-on: "ubuntu-latest"
    environment:
      name: pypi
      url: https://pypi.org/p/orbiter-community-translations
    permissions:
      id-token:
        write
    steps:
      - uses: actions/download-artifact@v4
      - run: ls -R && rm -f dist/*.pyz
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
